config/routes.rb
Music::Application.routes.draw do
  
  root :to => 'main#index'
  match 'music', :to => "music#index"
  match '/music/:title', :to => "music#music", as: 'piece'
  
  resources :music do
    resource :music
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/piece.rb
class Piece < ActiveRecord::Base
  attr_accessible :description, :featured, :summary, :title, :piece_section_ids, :piece_sections_attributes
  validates_presence_of :title
  validates_uniqueness_of :title
  has_many :piece_sections, :dependent => :destroy
  accepts_nested_attributes_for :piece_sections
  scope :ordered, order("updated_at DESC")
end

app/models/piece_section.rb
class PieceSection < ActiveRecord::Base
  attr_accessible :audio_mp3, :audio_ogg, :audio_wav, :description, :piece_id, :priority, :title, :youtube
  mount_uploader :audio_mp3, AudioUploader
  mount_uploader :audio_wav, AudioUploader
  mount_uploader :audio_ogg, AudioUploader
  belongs_to :piece
  accepts_nested_attributes_for :piece
  scope :ordered, order("priority DESC")
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/music_controller.rb
class MusicController < ApplicationController
	def index
		@pieces = Piece.order("updated_at DESC")
		@featured_pieces = Piece.where(featured: true).order("updated_at DESC")
	end

	def music
		@piece = Piece.find_by_title(params[:title])
		@piece_sections = @piece.piece_sections
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/music_helper.rb
module MusicHelper
end

app/views/layouts/_header.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Example Music Site", root_path %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
      <li class="divider"></li>
      <li><%= link_to "Home", root_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Music", music_path %></li>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <header><%= render 'layouts/header' %></header>

    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>

app/views/music/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <img src="<%= asset_path 'composition.jpg' %>", alt="http://placehold.it/1000x400&text=[img]">
    <hr>


<% if @pieces.count > 0 %>
	<% if @featured_pieces.count > 0 %>
		<ul class="small-block-grid-1 medium-block-grid-2 large-block-grid-2">
			<% @featured_pieces.each do |piece| %>
				<li><h2><%= piece.title %></h2>
				<% unless piece.summary =="" %>
					<p><%= piece.summary %></p>
				<% end %>
				<a href="<%= piece_path(:title => piece.title) %>" class="button round">More</a></li>
			<% end %>
		</ul>
	<% end %>
	<ul class="small-block-grid-2 medium-block-grid-3 large-block-grid-4">
		<% (@pieces - @featured_pieces).each do |piece| %>
			<li><h2><%= piece.title %></h2>
			<% unless piece.summary =="" %>
				<p><%= piece.summary %></p>
			<% end %>
			<a href="<%= piece_path(:title => piece.title) %>" class="button round">More</a></li>
		<% end %>
	</ul>
<% end %>

  </div>
</div>

app/views/music/music.html.erb
<h1><%= @piece.title %></h1>
<p><%= @piece.description.html_safe %></p>
	<% @piece_sections.each do |piece_section| %>
		<% unless piece_section.title == "" %>
			<h3><%= piece_section.title %></h3>
		<% end %>
		<% unless piece_section.description == "" %>
			<p><%= piece_section.description %></p>
		<% end %>
		<% unless piece_section.youtube == "" %>
			<div class="small-10 small-centered columns">
				<div class="flex-video">
					<iframe width="420" height="315" frameborder="0" allowfullscreen="" src="<%= piece_section.youtube %>"></iframe>
				</div>
			</div>
		<% end %>
		<% if piece_section.audio_mp3? ||  piece_section.audio_wav? ||  piece_section.audio_ogg? %>
		<audio controls>
			<% if piece_section.audio_mp3? %>
				<source src="<%= piece_section.audio_mp3_url.to_s %>" type="audio/mpeg" />
			<% end %>
			<% if piece_section.audio_wav? %>
				<source src="<%= piece_section.audio_wav_url.to_s %>" type="audio/wav" />
			<% end %>
			<% if piece_section.audio_ogg? %>
				<source src="<%= piece_section.audio_ogg_url.to_s %>" type="audio/ogg" />
			<% end %>
			Your browser does not support this audio file.
		</audio controls>
	<% end %>
<% end %>